from app.repositories.dynamic_schema import (
    create_dynamic_schema,
    create_dynamic_schema_fields,
    create_dynamic_schema_version,
    get_dynamic_schema_by_id_for_update,
    get_dynamic_schema_by_key,
    get_dynamic_schema_by_key_for_update,
    get_dynamic_schema_version_for_update,
    get_dynamic_schema_version_with_fields,
    get_next_dynamic_schema_version_no,
    list_active_dynamic_schema_versions_for_update,
    get_project_by_id,
    get_project_member_for_project as get_dynamic_schema_project_member_for_project,
)
from app.repositories.entity import (
    create_entity,
    create_entity_alias,
    get_entity_alias_by_id_for_update,
    get_entity_by_id_for_update,
    get_entity_by_identity_for_update,
    get_entity_by_identity_hash_for_update,
    get_project_by_id as get_entity_project_by_id,
    get_project_member_for_project as get_entity_project_member_for_project,
    resolve_entity_alias,
    update_entity_alias,
)
from app.repositories.dynamic_schema_projection import (
    get_dynamic_schema_by_id as get_dynamic_schema_by_id_for_projection,
    get_dynamic_schema_version_with_fields_for_projection,
    list_facts_for_projection,
)
from app.repositories.fact import (
    create_fact,
    create_fact_evidence_links,
    create_fact_value,
    get_extraction_run_with_project,
    get_fact_by_identity,
    get_fact_by_id_for_update,
    get_fact_by_identity_for_update,
    get_fact_value_for_update,
    get_next_fact_version_no,
    get_project_member_for_project,
    list_source_evidences_with_context,
    update_fact,
    update_fact_value,
)
from app.repositories.document_content import (
    create_document_blocks,
    create_extraction_run,
    create_source_evidence,
    get_document_block_by_id,
    get_next_extraction_attempt_no,
    get_revision_for_extraction_update,
    get_source_evidence_by_offsets,
)
from app.repositories.document import (
    create_document,
    create_document_revision,
    get_document_for_project,
    get_document_for_update,
    get_latest_revision_for_document,
    get_revision_detail_for_project,
    list_documents_for_project,
)
from app.repositories.ingestion_validation import (
    create_risk_flags,
    create_validation_report,
)
from app.repositories.project import (
    create_project,
    create_project_member,
    get_project_by_slug,
    get_project_member_for_user_by_slug,
    get_project_for_user_by_slug,
    list_projects_for_user,
)
from app.repositories.processing_job import (
    create_processing_job,
    get_active_processing_job_for_update,
    get_active_user_by_id as get_active_user_by_id_for_processing_job,
    get_extraction_run_by_id,
    get_latest_extraction_run_for_revision,
    get_latest_processing_job_for_revision,
    get_latest_failed_processing_job,
    get_next_processing_job_attempt_no,
    get_processing_job_by_id,
    get_processing_job_by_id_for_update,
    get_processing_job_for_update,
    get_project_member_for_project as get_processing_job_project_member_for_project,
    get_revision_by_id,
    get_revision_for_processing_job_update,
)
from app.repositories.revision_admission import (
    get_active_user_by_id as get_active_user_by_id_for_revision_admission,
    get_latest_validation_report_for_update,
    get_project_member_for_project as get_revision_admission_project_member_for_project,
    get_revision_for_admission_update,
)
from app.repositories.revision_extraction import (
    get_latest_validation_report_for_update as get_latest_validation_report_for_extraction_update,
    get_revision_for_extraction_update as get_revision_for_project_extraction_update,
)
from app.repositories.user import (
    create_user,
    get_user_by_email,
    get_user_by_handle,
    get_user_by_id,
)

__all__ = [
    "get_user_by_id",
    "get_user_by_handle",
    "get_user_by_email",
    "create_user",
    "get_project_by_id",
    "get_dynamic_schema_project_member_for_project",
    "get_entity_project_by_id",
    "get_entity_project_member_for_project",
    "get_entity_by_identity_for_update",
    "get_entity_by_identity_hash_for_update",
    "get_entity_by_id_for_update",
    "get_entity_alias_by_id_for_update",
    "create_entity",
    "create_entity_alias",
    "update_entity_alias",
    "resolve_entity_alias",
    "get_dynamic_schema_by_id_for_projection",
    "get_dynamic_schema_version_with_fields_for_projection",
    "list_facts_for_projection",
    "get_dynamic_schema_by_id_for_update",
    "get_dynamic_schema_by_key",
    "get_dynamic_schema_by_key_for_update",
    "get_dynamic_schema_version_for_update",
    "list_active_dynamic_schema_versions_for_update",
    "create_dynamic_schema",
    "get_next_dynamic_schema_version_no",
    "create_dynamic_schema_version",
    "create_dynamic_schema_fields",
    "get_dynamic_schema_version_with_fields",
    "get_extraction_run_with_project",
    "list_source_evidences_with_context",
    "get_fact_by_identity",
    "get_fact_by_id_for_update",
    "get_fact_by_identity_for_update",
    "get_fact_value_for_update",
    "get_project_member_for_project",
    "create_fact",
    "get_next_fact_version_no",
    "create_fact_value",
    "create_fact_evidence_links",
    "update_fact",
    "update_fact_value",
    "get_revision_for_extraction_update",
    "get_next_extraction_attempt_no",
    "create_extraction_run",
    "create_document_blocks",
    "get_document_block_by_id",
    "get_source_evidence_by_offsets",
    "create_source_evidence",
    "list_documents_for_project",
    "get_document_for_project",
    "get_document_for_update",
    "get_latest_revision_for_document",
    "get_revision_detail_for_project",
    "create_document",
    "create_document_revision",
    "create_validation_report",
    "create_risk_flags",
    "list_projects_for_user",
    "get_project_by_slug",
    "get_project_member_for_user_by_slug",
    "get_project_for_user_by_slug",
    "create_project",
    "create_project_member",
    "get_revision_for_processing_job_update",
    "get_active_processing_job_for_update",
    "get_next_processing_job_attempt_no",
    "create_processing_job",
    "get_active_user_by_id_for_processing_job",
    "get_processing_job_project_member_for_project",
    "get_latest_extraction_run_for_revision",
    "get_latest_processing_job_for_revision",
    "get_latest_failed_processing_job",
    "get_processing_job_by_id",
    "get_processing_job_by_id_for_update",
    "get_processing_job_for_update",
    "get_extraction_run_by_id",
    "get_revision_by_id",
    "get_revision_for_admission_update",
    "get_latest_validation_report_for_update",
    "get_active_user_by_id_for_revision_admission",
    "get_revision_admission_project_member_for_project",
    "get_revision_for_project_extraction_update",
    "get_latest_validation_report_for_extraction_update",
]
